[versions]
kotlinTarget = "2.2"
javaTarget = "17"

kotlin = "2.2.21"
kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.9.0"

xemanticKotlinCore = "0.5.0"
xemanticKotlinTest = "1.15.2"
neo4j = "2025.10.1"
neo4jDriver = "6.0.2"
mockk = "1.14.6"

versionsPlugin = "0.53.0"
dokkaPlugin = "2.1.0"
mavenPublishPlugin = "0.35.0"
jreleaserPlugin = "1.20.0"
binaryCompatibilityValidatorPlugin = "0.18.1"
xemanticConventionsPlugin = "0.6.7"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
xemantic-kotlin-test = { module = "com.xemantic.kotlin:xemantic-kotlin-test", version.ref = "xemanticKotlinTest" }
xemantic-kotlin-core = { module = "com.xemantic.kotlin:xemantic-kotlin-core", version.ref = "xemanticKotlinCore" }
neo4j-driver = { module = "org.neo4j.driver:neo4j-java-driver",version.ref = "neo4jDriver" }
neo4j-harness = { module = "org.neo4j.test:neo4j-harness", version.ref = "neo4j" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-power-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
kotlinx-binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibilityValidatorPlugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublishPlugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaserPlugin" }
xemantic-conventions = { id = "com.xemantic.gradle.xemantic-conventions", version.ref = "xemanticConventionsPlugin" }
